### ISSUE TITLE
FeedParseError on some common public RSS feeds

### ISSUE THREAD

**Issue by paregorios** [NicolasLM/atoma#1]
RSS feeds from the New York Times and the Washington Post fail. Python 3.6.4. atoma 0.0.3.

Steps to reproduce:
```
>>> import atoma
>>> import requests
>>> response = requests.get('http://feeds.washingtonpost.com/rss/national')
>>> feed = atoma.parse_atom_bytes(response.content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/atom.py", line 267, in parse_atom_bytes
    return _parse_atom(root)
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/atom.py", line 214, in _parse_atom
    title = _get_text_construct(root, 'feed:title')
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/atom.py", line 112, in _get_text_construct
    child = get_child(element, name, optional)
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/utils.py", line 25, in get_child
    .format(name, element.tag)
atoma.utils.FeedParseError: Could not parse RSS channel: "feed:title" required in "rss"
>>> response = requests.get('http://rss.nytimes.com/services/xml/rss/nyt/Science.xml')
>>> feed = atoma.parse_atom_bytes(response.content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/atom.py", line 267, in parse_atom_bytes
    return _parse_atom(root)
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/atom.py", line 214, in _parse_atom
    title = _get_text_construct(root, 'feed:title')
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/atom.py", line 112, in _get_text_construct
    child = get_child(element, name, optional)
  File "/Envs/feedpod/lib/python3.6/site-packages/atoma/utils.py", line 25, in get_child
    .format(name, element.tag)
atoma.utils.FeedParseError: Could not parse RSS channel: "feed:title" required in "rss"
```

**Comment by paregorios** [comment]
Disregard. I see I'm calling the atom parser on an rss feed.
