### ISSUE TITLE
unable to import module

### ISSUE THREAD

**Issue by klaypigeon** [NicolasLM/atoma#10]
Python 3.5.5 (default, Jul 24 2018, 10:23:26)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
>>> import requests
>>> import atoma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/misc/home/mname/git/venv3/lib/python3.5/site-packages/atoma/__init__.py", line 1, in <module>
    from .atom import parse_atom_file, parse_atom_bytes
  File "/misc/home/mname/git/venv3/lib/python3.5/site-packages/atoma/atom.py", line 23
    text_type: str = attr.ib()
             ^
SyntaxError: invalid syntax

**Comment by klaypigeon** [comment]
Install output:
(venv3) [mname@utllbs001d git]$ pip install --force atoma
Collecting atoma
  Using cached https://files.pythonhosted.org/packages/5c/2d/17625a209759930d138a97648ec5821f5d1af4a68775708694251520cc83/atoma-0.0.17-py3-none-any.whl
Collecting defusedxml (from atoma)
  Using cached https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting python-dateutil (from atoma)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting attrs (from atoma)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->atoma)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: defusedxml, six, python-dateutil, attrs, atoma
  Found existing installation: defusedxml 0.6.0
    Uninstalling defusedxml-0.6.0:
      Successfully uninstalled defusedxml-0.6.0
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
  Found existing installation: python-dateutil 2.8.0
    Uninstalling python-dateutil-2.8.0:
      Successfully uninstalled python-dateutil-2.8.0
  Found existing installation: attrs 19.1.0
    Uninstalling attrs-19.1.0:
      Successfully uninstalled attrs-19.1.0
  Found existing installation: atoma 0.0.17
    Uninstalling atoma-0.0.17:
      Successfully uninstalled atoma-0.0.17
Successfully installed atoma-0.0.17 attrs-19.1.0 defusedxml-0.6.0 python-dateutil-2.8.0 six-1.12.0

**Comment by klaypigeon** [comment]
compatible 3.6+ closing issue. We are at 3.5.
